### ISSUE TITLE
loudspeaker config helper

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#14]
Hello I have prepared [do_config_files.py](https://github.com/Rsantct/pre.di.c/blob/master/bin_custom/do_config_files.py): a loudspeaker config helper script.

You can have a human readable YAML file where to define your multiway loudspeaker configuration:

[loudspeakers/example2ways+sub/example2ways+sub.yml](https://github.com/Rsantct/pre.di.c/blob/master/loudspeakers/example2ways/example2ways%2Bsub.yml)

Then the script generates `brutefir_config` and `speaker.yml` to pre.di.c to work:

~$ do_config_files.py 

```
 Usage:     do_config_files.py   loudspeakers/myLoudspeaker/  [ -w ] [ |less ]

            -w   Overwrites the existing 'speaker.yml' and 'brutefir_config',
                 otherwise '____.candidate' files will be provided.

 This generates low level files needed for pre.di.c to work, i.e.:

   'brutefir_config', 'speaker.yml'

 The following files are needed under the folder 'myLoudspeaker':

   - 'myLoudspeaker.yml':
     The complete full range, multiway, subwoofer loudspeaker definitions including
     pcm names, gain, delay and polarity, as well as target values for SLP and room EQ.

   - 'brutefir_settings.yml':
     General runtime options for Brutefir.

   -  and some '*.pcm' FIR files to be used for XO and DRC.

      (i) CONVENTIONS FOR NAMING *.pcm FIR FILES:

        XO:
          xo.someDescription.pcm

        DRC:
          drc.X_someDescription.pcm     Where X is the channel 'L' or 'R'

```

Some stuff 'ref_level_gain' and 'target_xxx_curve parameters' still need to be considered manually under `speaker.yml`.

Hope this helps.

**Comment by rripio** [comment]
I'll have an aye on your fork, although you know my preferences for a totally free configuration.
