### ISSUE TITLE
'input none' fails

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#16]
When issue the command `input none` a warning appears:

```
Warnings:
	 Something went wrong when changing input state
```

It seems that it is missed an early `return` inside `server_process.change_input()`:

```
    def change_input(input, state=state):

        state['input'] = input
        # if none disconnects all inputs
        if input == 'none':
            disconnect_inputs()
            return state                    <===== this one fix the problem
```

**Comment by rripio** [comment]
Done, thank you.
I've added a exception raising if no input is given, to make it consistent with other commands in similar cases. So *input* command would print:
```
Warnings:
	 Something went wrong when changing input state
```
