### ISSUE TITLE
Allowing commented out lines in config/scripts file

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#18]
A little mod will permit to comment out a whole line or something at the line tail in config/scripts

```
207             for line in [ x for x in open(bp.script_list_path) 
208                                 if not '#' in x.strip()[0] ]:

```

**Comment by rripio** [comment]
Great addition, thank you @Rsantct !

**Comment by rripio** [comment]
I forgot to change this in ~/bin/stopaudio.py also. Please be specific about which files must be changed :-)
