### ISSUE TITLE
mpd.py script can mask 'import mpd' when not installed python-mpd

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#20]
I have renamed `scripts/mpd.py` to `scripts/mpd_script.py` because the 'import mpd' statement does not fails if the `python-mpd` package were not installed, i.e. the fail will be masked. So no warnings abuot missing package will appear for us to notice it.

**Comment by rripio** [comment]
Curious, I would have thought that it could not happen since ~/scripts is not in the python search path.
Anyway, let's be in the safe side of things, and change the script name. Thanks.
