### ISSUE TITLE
ALSA players

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#21]
I propose to include a little function `update_asoundrc()` inside `startaudio.init_jack()` to manage this issue. It can be found [here](https://github.com/Rsantct/pre.di.c/blob/master/bin/startaudio.py).

**Comment by Rsantct** [comment]
Hello, having discussed off line about this, it seems to be more adecuated to prepare a loop in jack the same way as current loops for MPD or Mplayer. 

I will work on including a new custom script for example `scripts/alsa_players` in order to provide a common entry point for any player using the alsa to jack plugin. Then the above function under `startaudio.init_jack()` will be unnecessary.

**Comment by Rsantct** [comment]
Well. First of all, I have renamed this issue because the new treatment.

This is my proposal for players that uses ALSA as audio backend:

**`~/asoundrc`**
Here we set the alsa to jack plugin pointing to alsa_loop:input_1 & 2 as destination JACK ports

**`scripts/alsa2jack.py`**
This script provides the alsa_loop in JACK, in a similar way as `mpd_load.py` does.

**`bin/jack_loop.py`**
This is a new module similar to the current function `predic.jack_loop()`, but I have wrote it in a way that it self keeps the looping ports alive. No wait for ever loop inside `scripts/alsa2jack.py` is needed.
Maybe this new method can be adopted intro `predic.py` ¿?

**`config/inputs.yml`**
Here I have defined an input called 'spotify' that usues the alsa_loop ports, because my Spotify player is `librespot`, a back box embedded like player that uses ALSA as audio backend.

**Comment by rripio** [comment]
I'd love to have this function feasible without an infinite loop.
The problem is: function do not return while the loop is up, so any command that comes after the loop launching will not be executed. In other words, script runs the loop but not the player :-)
¿Any solutions to this?

**Comment by rripio** [comment]
We should struggle to mantein a common interface to scripts, so a new jack_loop function should be of universal use.

**Comment by Rsantct** [comment]
> 
> 
> I'd love to have this function feasible without an infinite loop.
> The problem is: function do not return while the loop is up, so any command that comes after the loop launching will not be executed. In other words, script runs the loop but not the player :-)
> ¿Any solutions to this?

Tried this works fine:

```
def start():
    """loads mpd"""

    # create jack loop for connections
    Popen( 'jack_loop.py mpd_loop'.split() )
    #time.sleep(gc.config['command_delay'])
    print('starting mpd')
    ...
    ...
```

Yes, it is an external command but immo it makes sense. MPD is an external player from the point of view of the preamp, so when MPD comes into scenery, it kindly ask for a port entry to the preamp.

Another approximation is to launch separatelly a bulk of loops in predic for players to connect into ... If the preamp's user likes this way he is free to do.

**Comment by Rsantct** [comment]
Yet another solution could be to use threading into `mpd_load.py`, but maybe too complex ;-)

**Comment by rripio** [comment]
No! That's the right way! :-) Now that you have imported the threading module you have the tool in your hand.

I think that calling a python function as an external program is better to be avoided.

**Comment by rripio** [comment]
> Another approximation is to launch separatelly a bulk of loops in predic for players to connect into ... If the preamp's user likes this way he is free to do.

Just a question. Is it neccessary to launch a loop for a player like plays to ALSA? I thought that the alsa to jack plugin creates some ports... Am I wrong?

**Comment by rripio** [comment]
Or... maybe it creates only when playing? That's the very reason for the mpd and mplayer loops, ports disappear when playing stops.

**Comment by Rsantct** [comment]
Well. As per me knowledge on the alsa2jack plugin:

- It is needed to define wich writable port in jack the plugin will connect to (inside `~/.asoundrc`). This is the reason for my initial proposal.
- The readable jack ports created by the plugin are secuentially named as per each plugin occurrence, i.e the name varies:

```
~$ jack_view_connections.py alsa

alsa_loop:output_1                    -->--   brutefir:in.L
alsa_loop:output_2                    -->--   brutefir:in.R
alsa-jack.rawjackP.30415.2:out_000    -->--   alsa_loop:input_1
alsa-jack.rawjackP.30415.2:out_001.   -->--   alsa_loop:input_2
```

were `30415.2` is the pid of the alsa player dot the secuence of playing that is increased +=1 for each playback sesion. Here `.2` because is the 3th time the player (librespot ~ spotify) uses the plugin.

**Comment by Rsantct** [comment]
Hi I have pull requested some mods to threading the jack loops for both MPD and ALSA players

Files are

- bin/predic.jack_loop()
- scripts/mpd_load.py
- scripts/alsa2jack.py
- .asoundrc

**Comment by Rsantct** [comment]
> 
> 
> Hi I have pull requested some mods to threading the jack loops for both MPD and ALSA players
> 
But still something to fix, work in progress..

**Comment by rripio** [comment]
Ok, I'm waiting :-)

**Comment by Rsantct** [comment]
Well, ready to test under pull request #26 

Some mods to threading the jack loops for both MPD and ALSA players

```
bin/predic.jack_loop()
scripts/mpd_load.py
scripts/alsa_loop_load.py
.asoundrc

```
Also leaving `time.sleep` under `stopaudio.py`

**Comment by Rsantct** [comment]
Closing after this has been updated into the master repo #26
