### ISSUE TITLE
code arrangement

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#29]
@rripio says:

Also, I think that we should discuss in advance a bit changes this big, that affects general distribution of code. That is, I would have rather have each player's specific code confined to it's own load script as much as possible.

That goes also for any auxiliary functions, and so leave the bin folder dedicated to the server, that is _player agnostic_.

Layers of functionality are to be as independent as possible from the server.

_Originally posted by @rripio in https://github.com/rripio/pre.di.c/pull/28#issuecomment-443886105_

**Comment by rripio** [comment]
Some neccesary instructions about extending python path or whatever could be given in a README.md file.

**Comment by Rsantct** [comment]
work in progress under my fork `code-arrang-ph2` branch

**Comment by rripio** [comment]
Ouch, we are duplicating efforts... We should talk more in advance...

**Comment by Rsantct** [comment]
Oooops, i'm sorry.

All is running ok on my branch `code-arrang-ph2` except the control web page that shows an strange slowness after moving all stuff to` ~/pre.di.c/`
