### ISSUE TITLE
Review and try everything PEQ

### ISSUE THREAD

**Issue by rripio** [rripio/pre.di.c#3]
There are wired paths to (now) predic folder, config files needs update YAML format, and a function in server_process.py is needed.

**Comment by Rsantct** [comment]
Hi, I plan to work on this, so if any ideas on the while let's share here ;-)

**Comment by Rsantct** [comment]
Ok, it works. Files can be found [here](https://github.com/Rsantct/pre.di.c/tree/peq).

A summary of changes:

- loudspeakers/..../speaker.yml

    Added PEQ section, example:

    PEQ:
        defeat: none       --> this is default generated by do_config_files.py ;-)
        peq1:   peq1.peq

- config/config.yml

    load_ecasound = True

- config/state

    Removed 'peq' and 'peqdefeat' keys

    New key 'PEQ_set'
    
- bin/predic.py

    show() function updated to use new PEQ_Set key

- config/PEQxxxxx 

    Templates updated

- bin/startaudio.py

    if gc.config['load_ecasound']: import peq_control

    init_state_settings()
        ...
        ...
        # new restore PEQ set section
        peq_control ....
        
- bin/peq_control.py

    Minimum python3 updates (socket, etc)
    
    PEQdefeat() function adapted
    
    TODO: translate functions names and code to english...
    
- bin/server_process.py

    Added 'peq': change_peq into the parse commands section
    
    A new function 'change_peq(PEQ_set, status)'
    
    A new command 'peq somePEQset' is processed now

**Comment by Rsantct** [comment]
Also, the control web page has been updated to show a PEQ selector when load_ecasound=True

**Comment by rripio** [comment]
Working, peq_control.py translated... :-)

**Comment by rripio** [comment]
Everything updated.

Thank you very much, @Rsantct :-)

**Comment by Rsantct** [comment]
Hi, thanks for translating to EN :-)

Somo minors needs to be corrected, please see Pull request #27
