### ISSUE TITLE
DVB.py script is broken after pull #27

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#30]
Hi @Rsantct , DVB.py script is broken by this merge, could you please review the script and update it?

_Originally posted by @rripio in https://github.com/rripio/pre.di.c/pull/27#issuecomment-443884277_

**Comment by rripio** [comment]
Hi, still broken. Loop is created but player doesn't load.

If the script is launched manually it works, but then mplayer runs in foreground, ie, the script do not return to command line.

**Comment by rripio** [comment]
Hi @Rsantct : Sorry, my mistake, I didn't updated the file correctly :-(
