### ISSUE TITLE
Error loading server_aux.py

### ISSUE THREAD

**Issue by rripio** [rripio/pre.di.c#33]
Hi @Rsantct : thanks for your efforts on the web page.

When loading predic this error arises, here reproduced manually:
predic@predic:~$ scripts/server_aux.py start
(server_aux) bad option

The result is that new functionalities of player communications do not work.

Also, on this line of loading script:
`Popen( ['server_aux.py'] ) # if this fails check your paths`
you could put the full path with the help of bin/basepaths.py
```
import basepaths as bp
---
path = bp.bin_folder
```
or something like that.

**Comment by Rsantct** [comment]
Ooops. Tried on my system it seems to work well:

```
Last login: Wed Dec  5 18:14:34 2018 from 192.168.1.36
predic@rpi3clac:~$ ps -ef | grep server_aux
predic     820     1  0 Dec04 ?        00:06:16 python3 /home/predic/bin/server_aux.py
predic   21753 21728  0 18:14 pts/0    00:00:00 grep server_aux
predic@rpi3clac:~$ scripts/server_aux.py stop
Killed
predic@rpi3clac:~$ scripts/server_aux.py start &
[1] 21784
predic@rpi3clac:~$ ps -ef | grep server_aux
predic   21785     1 12 18:15 pts/0    00:00:00 python3 /home/predic/bin/server_aux.py
predic   21791 21728  0 18:15 pts/0    00:00:00 grep server_aux
[1]+  Done                    scripts/server_aux.py start
predic@rpi3clac:~$ nc localhost 9988
player_get_meta
{ "player":"MPD", "artist":"Dave Holland", "album":"Selected Recordings", "title":"Four Winds" }quit
OK

predic@rpi3clac:~$ 

```

Let me see in deeper please.

**Comment by Rsantct** [comment]
Hello. I have updated my system from this site (rripio) master repo and things seems to work well.

I cannot reproduce your bug :-(

I have recently proposed an install scripts set #34  to easily update the system from the github files.

**Comment by rripio** [comment]
Ok, debugged. bin/server_aux.py didn't have executable bit. Git stores executable permission (and only that) and the final state has to be correct on the repo.
