### ISSUE TITLE
Offtopic

### ISSUE THREAD

**Issue by mantielero** [rripio/pre.di.c#44]
Hola Roberto,
No sé si te acuerdas de mí de la época del SweepScope. Ya estoy muy fuera de la acústica :o(. 

Me gustaría contactar contigo. Yo no he cambiado mi email (supongo que si buscas en tu correo por SweepScope, lo encontrarás). Si lo tienes ¿podrías escribirme? Yo tengo el tuyo de la época de "wanadoo", que ya no está operativo. Por no ponerlo por aquí a la vista de todo Internet!

Un saludo y me alegra ver (con envidia) que sigues operativo con el audio
Jose

**Comment by rripio** [comment]
¡Hombre, qué agradable sorpresa!
Tengo direcciones tuyas de una empresa, de wanadoo y de gmail :-)
Probaré con gmail...

**Comment by mantielero** [comment]
Cierro la issue!! Solved!! ;oP
