### ISSUE TITLE
Rewrite DVB launcher as a server

### ISSUE THREAD

**Issue by rripio** [rripio/pre.di.c#9]
Rewrite full DVB client as a server (state file: state_DVB.yml) and jack loop
creator.

**Comment by Rsantct** [comment]
Hi there!

Maybe not the proposed here, but I have recently adapted the current `scripts/DVB.py`. It uses a unique `config/DVB-T.yml` file for user presets configuration and also for recent used presets to be persistent. So `config/DVB-T_state.yml` is not used.

I have switched to the module `ruamer.yaml` that preserves comments and the order of yaml items when dumping.

It woks under a new folders structure, maybe not directly portable here :-/

Here it is:

https://github.com/Rsantct/pre.di.c/blob/master/pre.di.c/scripts/DVB.py
https://github.com/Rsantct/pre.di.c/blob/master/pre.di.c/config/DVB-T.yml.example

**Comment by rripio** [comment]
I think that your solution is the right one, a server is overwheelming for this tiny task.

In fact your code is not directly portable, and I prefer to have the state file and the config file separated (so I will not use ruamer) but I thank you for your code, that I will adapt ASAP.

So I close this, no server in prospect :-)
